### ISSUE TITLE
Read value from Slider

### ISSUE THREAD

**Issue by Sh1nde1ru** [jonas-zebari/interactive_slider#2]
Hey, I really like your slider.
But I can't really figure out how to read value from the slider.
I tried the "onChange" method you showed on the ReadMe page but that doesn't work.
Then I tried creating a controller but that didnt work either or I did it wrong.
I was hoping you could point me in the right direction.
Thanks :)

**Comment by jonas-zebari** [comment]
@Sh1nde1ru Hi, can you please supply some example code that you wrote that is not working for you? Thanks

**Comment by jonas-zebari** [comment]
@Sh1nde1ru Please see the new example as of 0.2.2 that shows using a controller to set/read the value. Thanks!
