### ISSUE TITLE
interactive_slider unable to update by Consumer

### ISSUE THREAD

**Issue by Zqiang12345** [jonas-zebari/interactive_slider#3]
interactive_slider unable to update by Consumer

**Comment by jonas-zebari** [comment]
Can you please provide some sort of explanation, description, or question? I don't understand what you mean.

**Comment by Zqiang12345** [comment]
How do I actively change the value of the progress bar

**Comment by jonas-zebari** [comment]
@Zqiang12345 Are you trying to change its value programmatically? In that case you can create an interactive slider controller and supply it to the widget.

**Comment by jonas-zebari** [comment]
With no additional info I am closing this issue for now. Thanks for understanding.
