### ISSUE TITLE
Please add enable / disable feature

### ISSUE THREAD

**Issue by louislamlam** [jonas-zebari/interactive_slider#5]
Is it possible to add a property like `enabled: false` to `InteractiveSlider` to disable interaction and animations?

`
InteractiveSlider(..., enabled: false)
`

This would be a great addition for scenarios where a static slider is desired.
Thanks for the awesome package!

**Comment by jonas-zebari** [comment]
@louislamlam with v0.3.0 I have added an enabled flag and a disabledOpacity option. Thank you for the feedback!
